"""Tests for the weight-space Kalman observer."""
import jax
import jax.numpy as jnp

from dbwm.inference.kalman import (
    kalman_predict,
    kalman_update,
    filter_sequence,
    open_loop_forecast,
)


def test_update_reduces_covariance():
    """A measurement update must not increase the covariance trace."""
    r = 5
    w = jnp.zeros(r)
    p = jnp.eye(r)
    phi_obs = jnp.ones(r)
    w_post, p_post = kalman_update(w, p, phi_obs, sigma_eps2=0.1)
    assert jnp.trace(p_post) <= jnp.trace(p) + 1e-6
    assert w_post.shape == (r,)


def test_predict_grows_covariance():
    """Prediction with process noise grows the covariance trace."""
    r = 4
    a = jnp.eye(r)
    q = 0.05 * jnp.eye(r)
    w, p = jnp.zeros(r), 0.1 * jnp.eye(r)
    _, p_pred = kalman_predict(w, p, a, q)
    assert jnp.trace(p_pred) >= jnp.trace(p)


def test_filter_sequence_tracks_state():
    """
    Filtering a sequence generated by the true dynamics with identity
    measurement should track the latent state closely.
    """
    key = jax.random.PRNGKey(0)
    r, t = 4, 30
    a = 0.95 * jax.random.orthogonal(key, r)
    w0 = jax.random.normal(jax.random.PRNGKey(1), (r,))
    states = [w0]
    for _ in range(t - 1):
        states.append(a @ states[-1])
    phi_obs = jnp.stack(states, axis=0)  # noiseless observations
    q = 1e-4 * jnp.eye(r)
    w_filt, p_filt = filter_sequence(phi_obs, a, q, sigma_eps2=1e-4)
    assert w_filt.shape == (t, r)
    assert jnp.allclose(w_filt[-1], states[-1], atol=1e-1)


def test_open_loop_forecast_covariance_grows():
    """Open-loop covariance trace is non-decreasing over the horizon."""
    r = 4
    a = jnp.eye(r)
    q = 0.02 * jnp.eye(r)
    w0 = jnp.ones(r)
    w_fc, p_fc = open_loop_forecast(w0, a, q, horizon=6, gamma_dyn=0.1)
    traces = jnp.array([jnp.trace(p_fc[k]) for k in range(6)])
    assert bool(jnp.all(jnp.diff(traces) >= -1e-6))
